import 'dart:io';

import 'package:flutter_archgen/flutter_archgen.dart';
import 'package:test/test.dart';

void main() {
  group('ArchitectureGenerator', () {
    late Directory tempDir;
    late ArchitectureGenerator generator;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp(
        'flutter_archgen_fixture_',
      );
      generator = ArchitectureGenerator();
      await _writeFlutterPubspec(tempDir, 'fixture_app');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('preserves user-owned files unless force is enabled', () async {
      final mainFile = File('${tempDir.path}/lib/main.dart');
      await mainFile.parent.create(recursive: true);
      await mainFile.writeAsString('void main() {}');

      final summary = await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
      );

      expect(mainFile.readAsStringSync(), equals('void main() {}'));
      expect(summary.skippedPaths, contains('lib/main.dart'));
    });

    test('adds the generated README section once', () async {
      final readme = File('${tempDir.path}/README.md');
      await readme.writeAsString('# Fixture App');

      await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
      );

      final contents = readme.readAsStringSync();
      expect(contents, contains('Generated Architecture'));
      expect(
        RegExp('Generated by flutter_archgen\\.').allMatches(contents).length,
        equals(1),
      );
    });

    test('enables firebase dependencies when crashlytics is requested', () async {
      await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: true,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
      );

      final pubspec = File('${tempDir.path}/pubspec.yaml').readAsStringSync();
      expect(pubspec, contains('firebase_core'));
      expect(pubspec, contains('firebase_crashlytics'));
      expect(
        File(
          '${tempDir.path}/lib/core/monitoring/crashlytics_monitoring_service.dart',
        ).existsSync(),
        isTrue,
      );
    });

    test('rejects invalid flavor names before generation', () {
      expect(
        () => GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,bad-flavor',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
        throwsA(isA<FormatException>()),
      );
    });

    test('rejects non-flutter targets', () async {
      await File('${tempDir.path}/pubspec.yaml').writeAsString('''
name: plain_dart
environment:
  sdk: ">=3.3.0 <4.0.0"
''');

      expect(
        () => generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: false,
            enableRemoteConfig: false,
            enableSentry: false,
            enableCrashlytics: false,
            enableNotifications: false,
            enableDeviceInfo: false,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        ),
        throwsA(isA<StateError>()),
      );
    });

    test(
      'writes robust env and injection templates for optional monitoring',
      () async {
        await generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: true,
            enableRemoteConfig: true,
            enableSentry: true,
            enableCrashlytics: true,
            enableNotifications: false,
            enableDeviceInfo: true,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        );

        final envContents = File(
          '${tempDir.path}/lib/core/config/env.dart',
        ).readAsStringSync();
        final injectionContents = File(
          '${tempDir.path}/lib/core/di/injection.config.dart',
        ).readAsStringSync();

        expect(envContents, contains('double.tryParse('));
        expect(envContents, contains('String get flavorName => flavor.value;'));
        expect(injectionContents, contains('registerSingleton<AppEnv>(env);'));
        expect(
          injectionContents,
          contains("import 'package:device_info_plus/device_info_plus.dart';"),
        );
      },
    );
  });
}

Future<void> _writeFlutterPubspec(Directory directory, String packageName) {
  return File('${directory.path}/pubspec.yaml').writeAsString('''
name: $packageName
description: Test app
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
''');
}
