import 'dart:io';

import 'package:flutter_archgen/flutter_archgen.dart';
import 'package:test/test.dart';

void main() {
  group('ArchitectureGenerator', () {
    late Directory tempDir;
    late ArchitectureGenerator generator;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp(
        'flutter_archgen_fixture_',
      );
      generator = ArchitectureGenerator();
      await _writeFlutterPubspec(tempDir, 'fixture_app');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('preserves user-owned files unless force is enabled', () async {
      final mainFile = File('${tempDir.path}/lib/main.dart');
      await mainFile.parent.create(recursive: true);
      await mainFile.writeAsString('void main() {}');

      final summary = await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
      );

      expect(mainFile.readAsStringSync(), equals('void main() {}'));
      expect(summary.skippedPaths, contains('lib/main.dart'));
    });

    test('adds the generated README section once', () async {
      final readme = File('${tempDir.path}/README.md');
      await readme.writeAsString('# Fixture App');

      await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
      );

      final contents = readme.readAsStringSync();
      expect(contents, contains('Generated Architecture'));
      expect(
        RegExp('Generated by flutter_archgen\\.').allMatches(contents).length,
        equals(1),
      );
    });

    test('enables firebase dependencies when crashlytics is requested', () async {
      await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: true,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
      );

      final pubspec = File('${tempDir.path}/pubspec.yaml').readAsStringSync();
      expect(pubspec, contains('firebase_core'));
      expect(pubspec, contains('firebase_crashlytics'));
      expect(
        File(
          '${tempDir.path}/lib/core/monitoring/crashlytics_monitoring_service.dart',
        ).existsSync(),
        isTrue,
      );
    });

    test(
      'removes obsolete generated firebase wrapper files on rerun',
      () async {
        final obsoletePaths = <String>[
          'lib/core/di/modules/firebase_module.dart',
          'lib/core/services/firebase/app_firebase_service.dart',
          'lib/core/services/firebase/remote_config_service.dart',
        ];

        for (final relativePath in obsoletePaths) {
          final file = File('${tempDir.path}/$relativePath');
          await file.parent.create(recursive: true);
          await file.writeAsString('// Generated by flutter_archgen.\n');
        }

        final summary = await generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: true,
            enableRemoteConfig: true,
            enableSentry: false,
            enableCrashlytics: false,
            enableNotifications: false,
            enableDeviceInfo: false,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        );

        for (final relativePath in obsoletePaths) {
          expect(File('${tempDir.path}/$relativePath').existsSync(), isFalse);
        }
        expect(summary.updatedCount, greaterThanOrEqualTo(4));
      },
    );

    test(
      'generates firestore and remote config abstractions with DI-backed implementations',
      () async {
        await generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: true,
            enableRemoteConfig: true,
            enableSentry: false,
            enableCrashlytics: false,
            enableNotifications: false,
            enableDeviceInfo: false,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        );

        final firestoreService = File(
          '${tempDir.path}/lib/core/services/firebase/firestore/firebase_firestore_service.dart',
        ).readAsStringSync();
        final firestoreServiceImpl = File(
          '${tempDir.path}/lib/core/services/firebase/firestore/firebase_firestore_service_impl.dart',
        ).readAsStringSync();
        final remoteConfigService = File(
          '${tempDir.path}/lib/core/services/firebase/remote_config/firebase_remote_config_service.dart',
        ).readAsStringSync();
        final remoteConfigServiceImpl = File(
          '${tempDir.path}/lib/core/services/firebase/remote_config/firebase_remote_config_service_impl.dart',
        ).readAsStringSync();
        final bootstrap = File(
          '${tempDir.path}/lib/app/bootstrap.dart',
        ).readAsStringSync();

        expect(
          firestoreService,
          contains('abstract class FirebaseFirestoreService'),
        );
        expect(
          firestoreService,
          contains('Future<Result<void>> createDocument({'),
        );
        expect(
          firestoreService,
          contains('Future<List<Map<String, dynamic>>> getDocuments({'),
        );
        expect(
          firestoreServiceImpl,
          contains('class FirebaseFirestoreServiceImpl'),
        );
        expect(
          firestoreServiceImpl,
          contains('@LazySingleton(as: FirebaseFirestoreService)'),
        );
        expect(
          firestoreServiceImpl,
          contains('implements FirebaseFirestoreService'),
        );
        expect(
          firestoreServiceImpl,
          contains('return Result<void>.success(null);'),
        );

        expect(
          remoteConfigService,
          contains('abstract class FirebaseRemoteConfigService'),
        );
        expect(
          remoteConfigService,
          contains('Future<bool> fetchAndActivate();'),
        );
        expect(
          remoteConfigService,
          contains('Map<String, Object> defaults = const <String, Object>{},'),
        );
        expect(
          remoteConfigServiceImpl,
          contains('class FirebaseRemoteConfigServiceImpl'),
        );
        expect(
          remoteConfigServiceImpl,
          contains('@LazySingleton(as: FirebaseRemoteConfigService)'),
        );
        expect(
          remoteConfigServiceImpl,
          contains('implements FirebaseRemoteConfigService'),
        );
        expect(
          remoteConfigServiceImpl,
          contains("return _remoteConfig.fetchAndActivate();"),
        );
        expect(bootstrap, contains('await Firebase.initializeApp();'));
        expect(bootstrap, isNot(contains('AppFirebaseService')));
        expect(
          File(
            '${tempDir.path}/lib/core/services/firebase/app_firebase_service.dart',
          ).existsSync(),
          isFalse,
        );
        expect(
          File(
            '${tempDir.path}/lib/core/di/modules/firebase_module.dart',
          ).existsSync(),
          isFalse,
        );
      },
    );

    test('generates Hive and SQLite CRUD services when enabled', () async {
      await generator.generate(
        GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,prod',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: true,
          enableSqlite: true,
          force: false,
          skipPubGet: true,
        ),
      );

      final hiveService = File(
        '${tempDir.path}/lib/core/services/cache/hive_cache_service.dart',
      ).readAsStringSync();
      final hiveServiceImpl = File(
        '${tempDir.path}/lib/core/services/cache/hive_cache_service_impl.dart',
      ).readAsStringSync();
      final sqliteService = File(
        '${tempDir.path}/lib/core/services/database/app_database_service.dart',
      ).readAsStringSync();
      final sqliteServiceImpl = File(
        '${tempDir.path}/lib/core/services/database/app_database_service_impl.dart',
      ).readAsStringSync();

      expect(hiveService, contains('Future<void> create<T>('));
      expect(hiveService, contains('Future<T?> read<T>('));
      expect(hiveService, contains('Future<Map<String, T>> readAll<T>('));
      expect(hiveService, contains('Future<void> update<T>('));
      expect(
        hiveService,
        contains('Future<void> delete(String boxName, String key)'),
      );
      expect(hiveService, contains('abstract class HiveCacheService'));
      expect(hiveServiceImpl, contains('class HiveCacheServiceImpl'));
      expect(hiveServiceImpl, contains('@LazySingleton(as: HiveCacheService)'));
      expect(hiveServiceImpl, contains('implements HiveCacheService'));

      expect(sqliteService, contains('Future<int> create('));
      expect(
        sqliteService,
        contains('Future<List<Map<String, Object?>>> read('),
      );
      expect(
        sqliteService,
        contains('Future<Map<String, Object?>?> readById('),
      );
      expect(sqliteService, contains('Future<int> update('));
      expect(sqliteService, contains('Future<int> delete('));
      expect(sqliteService, contains('Future<T> transaction<T>('));
      expect(sqliteService, contains('abstract class AppDatabaseService'));
      expect(sqliteServiceImpl, contains('class AppDatabaseServiceImpl'));
      expect(
        sqliteServiceImpl,
        contains('@LazySingleton(as: AppDatabaseService)'),
      );
      expect(sqliteServiceImpl, contains('implements AppDatabaseService'));
    });

    test(
      'generates preference and secure storage abstractions with DI-backed implementations',
      () async {
        await generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: false,
            enableRemoteConfig: false,
            enableSentry: false,
            enableCrashlytics: false,
            enableNotifications: false,
            enableDeviceInfo: false,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        );

        final appPreferences = File(
          '${tempDir.path}/lib/core/services/preferences/app_preferences.dart',
        ).readAsStringSync();
        final appPreferencesImpl = File(
          '${tempDir.path}/lib/core/services/preferences/app_preferences_impl.dart',
        ).readAsStringSync();
        final secureStorageService = File(
          '${tempDir.path}/lib/core/services/security/secure_storage_service.dart',
        ).readAsStringSync();
        final secureStorageServiceImpl = File(
          '${tempDir.path}/lib/core/services/security/secure_storage_service_impl.dart',
        ).readAsStringSync();
        final storageModule = File(
          '${tempDir.path}/lib/core/di/modules/storage_module.dart',
        ).readAsStringSync();

        expect(appPreferences, contains('abstract class AppPreferences'));
        expect(
          appPreferences,
          contains('Future<bool> writeString(String key, String value);'),
        );
        expect(appPreferencesImpl, contains('class AppPreferencesImpl'));
        expect(
          appPreferencesImpl,
          contains('@LazySingleton(as: AppPreferences)'),
        );
        expect(appPreferencesImpl, contains('implements AppPreferences'));

        expect(
          secureStorageService,
          contains('abstract class SecureStorageService'),
        );
        expect(
          secureStorageService,
          contains('Future<void> write(String key, String value);'),
        );
        expect(
          secureStorageServiceImpl,
          contains('class SecureStorageServiceImpl'),
        );
        expect(
          secureStorageServiceImpl,
          contains('@LazySingleton(as: SecureStorageService)'),
        );
        expect(
          secureStorageServiceImpl,
          contains('implements SecureStorageService'),
        );

        expect(
          storageModule,
          isNot(contains('AppPreferences appPreferences(')),
        );
        expect(
          storageModule,
          isNot(contains('SecureStorageService secureStorageService(')),
        );
        expect(
          storageModule,
          contains(
            'TokenStorage tokenStorage(SecureStorageService secureStorageService)',
          ),
        );
      },
    );

    test(
      'generates shorebird and fastlane release scaffolding when enabled',
      () async {
        final summary = await generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,staging,prod',
            enableFirebase: false,
            enableRemoteConfig: false,
            enableSentry: false,
            enableCrashlytics: false,
            enableNotifications: false,
            enableDeviceInfo: false,
            enableHive: false,
            enableSqlite: false,
            enableShorebird: true,
            enableFastlane: true,
            force: false,
            skipPubGet: true,
            organization: 'com.example.orbit',
          ),
        );

        final shorebirdReadme = File(
          '${tempDir.path}/tool/release/shorebird/README.md',
        ).readAsStringSync();
        final shorebirdYaml = File(
          '${tempDir.path}/shorebird.yaml.example',
        ).readAsStringSync();
        final appfile = File(
          '${tempDir.path}/fastlane/Appfile',
        ).readAsStringSync();
        final fastfile = File(
          '${tempDir.path}/fastlane/Fastfile',
        ).readAsStringSync();
        final fastlaneReadme = File(
          '${tempDir.path}/fastlane/README.md',
        ).readAsStringSync();

        expect(
          shorebirdReadme,
          contains('shorebird release android --flavor prod'),
        );
        expect(shorebirdYaml, contains('app_id: your-shorebird-app-id'));
        expect(
          appfile,
          contains(
            "app_identifier(ENV['APP_IDENTIFIER'] || 'com.example.orbit.fixture_app')",
          ),
        );
        expect(
          fastfile,
          contains("flutter build appbundle --flavor #{flavor}"),
        );
        expect(
          fastlaneReadme,
          contains('bundle exec fastlane android internal flavor:prod'),
        );
        expect(
          summary.nextSteps,
          contains(
            'review `tool/release/shorebird/README.md` and run `shorebird init`',
          ),
        );
        expect(
          summary.nextSteps,
          contains('review `fastlane/README.md` and run `bundle install`'),
        );
      },
    );

    test('rejects invalid flavor names before generation', () {
      expect(
        () => GenerationConfig.fromArguments(
          targetDirectory: tempDir,
          flavorCsv: 'dev,bad-flavor',
          enableFirebase: false,
          enableRemoteConfig: false,
          enableSentry: false,
          enableCrashlytics: false,
          enableNotifications: false,
          enableDeviceInfo: false,
          enableHive: false,
          enableSqlite: false,
          force: false,
          skipPubGet: true,
        ),
        throwsA(isA<FormatException>()),
      );
    });

    test('rejects non-flutter targets', () async {
      await File('${tempDir.path}/pubspec.yaml').writeAsString('''
name: plain_dart
environment:
  sdk: ">=3.3.0 <4.0.0"
''');

      expect(
        () => generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: false,
            enableRemoteConfig: false,
            enableSentry: false,
            enableCrashlytics: false,
            enableNotifications: false,
            enableDeviceInfo: false,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        ),
        throwsA(isA<StateError>()),
      );
    });

    test(
      'writes robust env and injection templates for optional monitoring',
      () async {
        await generator.generate(
          GenerationConfig.fromArguments(
            targetDirectory: tempDir,
            flavorCsv: 'dev,prod',
            enableFirebase: true,
            enableRemoteConfig: true,
            enableSentry: true,
            enableCrashlytics: true,
            enableNotifications: false,
            enableDeviceInfo: true,
            enableHive: false,
            enableSqlite: false,
            force: false,
            skipPubGet: true,
          ),
        );

        final envContents = File(
          '${tempDir.path}/lib/core/config/env.dart',
        ).readAsStringSync();
        final injectionContents = File(
          '${tempDir.path}/lib/core/di/injection.dart',
        ).readAsStringSync();

        expect(envContents, contains('double.tryParse('));
        expect(envContents, contains('String get flavorName => flavor.value;'));
        expect(injectionContents, contains('registerSingleton<AppEnv>(env);'));
        expect(
          injectionContents,
          contains('@InjectableInit(preferRelativeImports: true)'),
        );
      },
    );
  });
}

Future<void> _writeFlutterPubspec(Directory directory, String packageName) {
  return File('${directory.path}/pubspec.yaml').writeAsString('''
name: $packageName
description: Test app
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
''');
}
