import 'package:flutter_archgen/src/generator/architecture_generator.dart';
import 'package:flutter_archgen/src/generator/file_manifest.dart';

class TemplateCatalog {
  static const String marker = 'Generated by flutter_archgen.';

  List<GeneratedFile> build(ResolvedGenerationConfig resolved) {
    final files = <GeneratedFile>[
      _dartFile('lib/main.dart', _mainDart(resolved)),
      _dartFile('lib/app/app.dart', _appDart(resolved)),
      _dartFile('lib/app/bootstrap.dart', _bootstrapDart(resolved)),
      _dartFile('lib/app/app_router.dart', _appRouterDart(resolved)),
      _dartFile('lib/app/theme/app_theme.dart', _appThemeDart(resolved)),
      _dartFile('lib/core/config/env.dart', _envDart(resolved)),
      _dartFile('lib/core/config/flavor.dart', _flavorDart(resolved)),
      _dartFile('lib/core/di/injection.dart', _injectionDart(resolved)),
      _dartFile(
        'lib/core/di/modules/monitoring_module.dart',
        _monitoringModuleDart(resolved),
      ),
      _dartFile(
        'lib/core/di/modules/service_module.dart',
        _serviceModuleDart(resolved),
      ),
      _dartFile(
        'lib/core/di/modules/storage_module.dart',
        _storageModuleDart(resolved),
      ),
      _dartFile('lib/core/error/app_failure.dart', _appFailureDart()),
      _dartFile(
        'lib/core/error/global_error_mapper.dart',
        _globalErrorMapperDart(resolved),
      ),
      _dartFile('lib/core/feedback/app_haptics.dart', _appHapticsDart()),
      _dartFile(
        'lib/core/lifecycle/app_lifecycle_manager.dart',
        _lifecycleManagerDart(resolved),
      ),
      _dartFile('lib/core/logging/app_logger.dart', _appLoggerDart()),
      _dartFile('lib/core/logging/app_logger_impl.dart', _appLoggerImplDart()),
      _dartFile('lib/core/monitoring/app_monitor.dart', _appMonitorDart()),
      _dartFile(
        'lib/core/monitoring/app_monitor_impl.dart',
        _appMonitorImplDart(resolved),
      ),
      _dartFile('lib/core/network/dio_client.dart', _dioClientDart(resolved)),
      _dartFile(
        'lib/core/network/network_config.dart',
        _networkConfigDart(resolved),
      ),
      _dartFile(
        'lib/core/network/network_constants.dart',
        _networkConstantsDart(),
      ),
      _dartFile(
        'lib/core/network/interceptors/auth_interceptor.dart',
        _authInterceptorDart(resolved),
      ),
      _dartFile(
        'lib/core/network/interceptors/logging_interceptor.dart',
        _loggingInterceptorDart(resolved),
      ),
      _dartFile(
        'lib/core/network/interceptors/retry_interceptor.dart',
        _retryInterceptorDart(resolved),
      ),
      _dartFile(
        'lib/core/network/models/api_error_response.dart',
        _apiErrorResponseDart(),
      ),
      _dartFile(
        'lib/core/network/models/request_options.dart',
        _requestOptionsDart(),
      ),
      _dartFile(
        'lib/core/network/services/api_client.dart',
        _apiClientDart(resolved),
      ),
      _dartFile(
        'lib/core/network/services/api_client_impl.dart',
        _apiClientImplDart(resolved),
      ),
      _dartFile(
        'lib/core/network/services/token_provider.dart',
        _tokenProviderDart(resolved),
      ),
      _dartFile(
        'lib/core/network/services/token_storage.dart',
        _tokenStorageDart(resolved),
      ),
      _dartFile(
        'lib/core/network/utils/multipart_builder.dart',
        _multipartBuilderDart(),
      ),
      _dartFile(
        'lib/core/network/utils/network_error_mapper.dart',
        _networkErrorMapperDart(),
      ),
      _dartFile(
        'lib/core/network/utils/request_validator.dart',
        _requestValidatorDart(resolved),
      ),
      _dartFile(
        'lib/core/services/preferences/app_preferences.dart',
        _appPreferencesDart(),
      ),
      _dartFile(
        'lib/core/services/preferences/app_preferences_impl.dart',
        _appPreferencesImplDart(resolved),
      ),
      _dartFile(
        'lib/core/services/security/secure_storage_service.dart',
        _secureStorageServiceDart(),
      ),
      _dartFile(
        'lib/core/services/security/secure_storage_service_impl.dart',
        _secureStorageServiceImplDart(resolved),
      ),
      _dartFile('lib/core/utils/result.dart', _resultDart(resolved)),
      _dartFile(
        'lib/shared/constants/app_strings.dart',
        _appStringsDart(resolved),
      ),
      _dartFile('lib/shared/constants/box_constants.dart', _boxConstantsDart()),
      _dartFile(
        'lib/shared/constants/route_constants.dart',
        _routeConstantsDart(),
      ),
      _dartFile(
        'lib/shared/constants/session_constants.dart',
        _sessionConstantsDart(),
      ),
      _dartFile(
        'lib/shared/design_system/design_tokens.dart',
        _designTokensDart(),
      ),
      _dartFile(
        'lib/shared/extensions/date_format_extension.dart',
        _dateFormatExtensionDart(),
      ),
      _dartFile(
        'lib/shared/extensions/string_extensions.dart',
        _stringExtensionsDart(),
      ),
      _dartFile('lib/shared/models/app_session.dart', _appSessionDart()),
      _dartFile('lib/shared/utils/screen_utils.dart', _screenUtilsDart()),
      _dartFile('lib/shared/widgets/custom_app_bar.dart', _customAppBarDart()),
      _dartFile('lib/shared/widgets/custom_dialog.dart', _customDialogDart()),
      _dartFile(
        'lib/shared/widgets/custom_snackbar.dart',
        _customSnackbarDart(),
      ),
      _dartFile(
        'lib/shared/widgets/custom_text_field.dart',
        _customTextFieldDart(),
      ),
      _dartFile('lib/shared/widgets/loading_view.dart', _loadingViewDart()),
      _markdownFile('lib/features/README.md', _featuresReadme()),
      _dartFile(
        'test/architecture_smoke_test.dart',
        _architectureSmokeTestDart(resolved),
      ),
      _yamlFile('analysis_options.yaml', _analysisOptionsYaml()),
      _yamlFile('build.yaml', _buildYaml()),
      _markdownFile(
        'README.md',
        _generatedReadmeSection(resolved),
        appendIfExists: true,
      ),
    ];

    if (resolved.config.enableDeviceInfo) {
      files
        ..add(
          _dartFile(
            'lib/core/di/modules/device_info_module.dart',
            _deviceInfoModuleDart(resolved),
          ),
        )
        ..add(
          _dartFile(
            'lib/core/services/device_info/app_device_info_service.dart',
            _deviceInfoServiceDart(),
          ),
        );
    }

    if (resolved.config.enableFirebase) {
      files
        ..add(
          _dartFile(
            'lib/core/services/firebase/firestore/firebase_firestore_service.dart',
            _firebaseFirestoreServiceDart(resolved),
          ),
        )
        ..add(
          _dartFile(
            'lib/core/services/firebase/firestore/firebase_firestore_service_impl.dart',
            _firebaseFirestoreServiceImplDart(resolved),
          ),
        );
    }

    if (resolved.config.enableRemoteConfig) {
      files
        ..add(
          _dartFile(
            'lib/core/services/firebase/remote_config/firebase_remote_config_service.dart',
            _remoteConfigServiceDart(resolved),
          ),
        )
        ..add(
          _dartFile(
            'lib/core/services/firebase/remote_config/firebase_remote_config_service_impl.dart',
            _remoteConfigServiceImplDart(resolved),
          ),
        );
    }

    if (resolved.config.enableSentry) {
      files
        ..add(
          _dartFile(
            'lib/core/monitoring/sentry_monitoring_service.dart',
            _sentryMonitoringServiceDart(resolved),
          ),
        )
        ..add(
          _textFile('sentry.properties.example', _sentryPropertiesExample()),
        );
    }

    if (resolved.config.enableCrashlytics) {
      files.add(
        _dartFile(
          'lib/core/monitoring/crashlytics_monitoring_service.dart',
          _crashlyticsMonitoringServiceDart(resolved),
        ),
      );
    }

    if (resolved.config.enableHive) {
      files
        ..add(
          _dartFile(
            'lib/core/services/cache/hive_cache_service.dart',
            _hiveCacheServiceDart(),
          ),
        )
        ..add(
          _dartFile(
            'lib/core/services/cache/hive_cache_service_impl.dart',
            _hiveCacheServiceImplDart(resolved),
          ),
        );
    }

    if (resolved.config.enableSqlite) {
      files
        ..add(
          _dartFile(
            'lib/core/services/database/app_database_service.dart',
            _databaseServiceDart(),
          ),
        )
        ..add(
          _dartFile(
            'lib/core/services/database/app_database_service_impl.dart',
            _databaseServiceImplDart(resolved),
          ),
        );
    }

    if (resolved.config.enableNotifications) {
      files.add(
        _dartFile(
          'lib/core/notifications/app_notification_service.dart',
          _notificationServiceDart(),
        ),
      );
    }

    if (resolved.config.enableShorebird) {
      files
        ..add(
          _markdownFile(
            'tool/release/shorebird/README.md',
            _shorebirdReadme(resolved),
          ),
        )
        ..add(
          _yamlFile('shorebird.yaml.example', _shorebirdYamlExample(resolved)),
        );
    }

    if (resolved.config.enableFastlane) {
      files
        ..add(_textFile('Gemfile', _fastlaneGemfile()))
        ..add(_textFile('fastlane/Appfile', _fastlaneAppfile(resolved)))
        ..add(_textFile('fastlane/Fastfile', _fastlaneFastfile(resolved)))
        ..add(_markdownFile('fastlane/README.md', _fastlaneReadme(resolved)));
    }

    return files;
  }

  GeneratedFile _dartFile(String path, String body) {
    return GeneratedFile(
      path: path,
      contents: '// $marker\n\n$body',
      ownershipMarker: marker,
    );
  }

  GeneratedFile _markdownFile(
    String path,
    String body, {
    bool appendIfExists = false,
  }) {
    return GeneratedFile(
      path: path,
      contents: '<!-- $marker -->\n\n$body',
      ownershipMarker: marker,
      appendIfExists: appendIfExists,
    );
  }

  GeneratedFile _yamlFile(String path, String body) {
    return GeneratedFile(
      path: path,
      contents: '# $marker\n\n$body',
      ownershipMarker: marker,
    );
  }

  GeneratedFile _textFile(String path, String body) {
    return GeneratedFile(
      path: path,
      contents: '# $marker\n\n$body',
      ownershipMarker: marker,
    );
  }

  String _packageImport(ResolvedGenerationConfig resolved, String filePath) {
    return 'package:${resolved.packageName}/$filePath';
  }

  String _defaultApplicationId(ResolvedGenerationConfig resolved) {
    final org = resolved.config.organization?.trim();
    final prefix = org == null || org.isEmpty ? 'com.example' : org;
    return '$prefix.${resolved.packageName}';
  }

  String _releaseFlavor(ResolvedGenerationConfig resolved) {
    final flavors = resolved.config.flavors;
    if (flavors.contains('prod')) {
      return 'prod';
    }
    return flavors.last;
  }

  String _mainDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'app/bootstrap.dart')}';

Future<void> main() async {
  await bootstrap();
}
''';
  }

  String _bootstrapDart(ResolvedGenerationConfig resolved) {
    final imports = <String>[
      "import 'package:flutter/material.dart';",
      "import 'package:flutter_riverpod/flutter_riverpod.dart';",
      if (resolved.config.enableFirebase)
        "import 'package:firebase_core/firebase_core.dart';",
      "import '${_packageImport(resolved, 'app/app.dart')}';",
      "import '${_packageImport(resolved, 'core/config/env.dart')}';",
      "import '${_packageImport(resolved, 'core/di/injection.dart')}';",
      "import '${_packageImport(resolved, 'core/lifecycle/app_lifecycle_manager.dart')}';",
      if (resolved.config.enableCrashlytics)
        "import '${_packageImport(resolved, 'core/monitoring/crashlytics_monitoring_service.dart')}';",
      if (resolved.config.enableSentry)
        "import '${_packageImport(resolved, 'core/monitoring/sentry_monitoring_service.dart')}';",
    ];

    final bootstrapInitializers = <String>[
      "  final env = AppEnv.fromEnvironment();",
      '  await configureDependencies(env);',
      '  getIt<AppLifecycleManager>().initialize();',
      '',
      '  Future<void> launchApp() async {',
      if (resolved.config.enableFirebase) '    await Firebase.initializeApp();',
      if (resolved.config.enableCrashlytics)
        '    await getIt<CrashlyticsMonitoringService>().initialize(env);',
      '    runApp(',
      '      ProviderScope(',
      '        child: App(appEnv: env),',
      '      ),',
      '    );',
      '  }',
      '',
      if (resolved.config.enableSentry)
        '  await getIt<SentryMonitoringService>().initialize(',
      if (resolved.config.enableSentry) '    env: env,',
      if (resolved.config.enableSentry) '    appRunner: launchApp,',
      if (resolved.config.enableSentry) '  );' else '  await launchApp();',
    ].join('\n');

    return '''
${imports.join('\n')}

Future<void> bootstrap() async {
  WidgetsFlutterBinding.ensureInitialized();
$bootstrapInitializers
}
''';
  }

  String _appDart(ResolvedGenerationConfig resolved) {
    final imports = <String>[
      "import 'package:flutter/material.dart';",
      if (resolved.config.enableSentry)
        "import 'package:sentry_flutter/sentry_flutter.dart';",
      "import '${_packageImport(resolved, 'app/app_router.dart')}';",
      "import '${_packageImport(resolved, 'app/theme/app_theme.dart')}';",
      "import '${_packageImport(resolved, 'core/config/env.dart')}';",
      "import '${_packageImport(resolved, 'shared/constants/route_constants.dart')}';",
    ];

    final navigatorObservers = resolved.config.enableSentry
        ? '''
      navigatorObservers: <NavigatorObserver>[
        SentryNavigatorObserver(),
      ],
'''
        : '';

    return '''
${imports.join('\n')}

class App extends StatelessWidget {
  const App({required this.appEnv, super.key});

  final AppEnv appEnv;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: appEnv.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      initialRoute: RouteConstants.root,
$navigatorObservers
      onGenerateRoute: AppRouter().onGenerateRoute,
    );
  }
}
''';
  }

  String _appRouterDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:flutter/material.dart';
import '${_packageImport(resolved, 'shared/constants/route_constants.dart')}';
import '${_packageImport(resolved, 'shared/widgets/custom_app_bar.dart')}';

class AppRouter {
  Route<dynamic> onGenerateRoute(RouteSettings settings) {
    final routeName = settings.name ?? RouteConstants.root;

    switch (routeName) {
      case RouteConstants.root:
        return _route('Root Shell', 'Connect startup and auth flows here.');
      case RouteConstants.home:
        return _route('Home Shell', 'Replace this page with your first feature.');
      case RouteConstants.settings:
        return _route('Settings Shell', 'Wire settings once the feature exists.');
      default:
        return _route('Not Found', 'No route registered for "\$routeName".');
    }
  }

  MaterialPageRoute<void> _route(String title, String message) {
    return MaterialPageRoute<void>(
      builder: (_) => PlaceholderShellPage(title: title, message: message),
    );
  }
}

class PlaceholderShellPage extends StatelessWidget {
  const PlaceholderShellPage({
    required this.title,
    required this.message,
    super.key,
  });

  final String title;
  final String message;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(title: title),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Text(
            message,
            textAlign: TextAlign.center,
          ),
        ),
      ),
    );
  }
}
''';
  }

  String _appThemeDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:flutter/material.dart';
import '${_packageImport(resolved, 'shared/design_system/design_tokens.dart')}';

class AppTheme {
  const AppTheme._();

  static ThemeData light() {
    final colorScheme = ColorScheme.fromSeed(
      seedColor: DesignTokens.primaryColor,
      brightness: Brightness.light,
      surface: DesignTokens.surfaceColor,
    );

    return ThemeData(
      colorScheme: colorScheme,
      scaffoldBackgroundColor: DesignTokens.backgroundColor,
      useMaterial3: true,
      appBarTheme: AppBarTheme(
        backgroundColor: colorScheme.surface,
        foregroundColor: colorScheme.onSurface,
        elevation: 0,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(DesignTokens.radiusMd),
          borderSide: BorderSide(color: colorScheme.outlineVariant),
        ),
      ),
    );
  }
}
''';
  }

  String _envDart(ResolvedGenerationConfig resolved) {
    final defaultFlavor = resolved.config.flavors.first;
    final enableSentryDefault = resolved.config.enableSentry ? 'true' : 'false';
    final enableCrashlyticsDefault = resolved.config.enableCrashlytics
        ? 'true'
        : 'false';
    return '''
import '${_packageImport(resolved, 'core/config/flavor.dart')}';

class AppEnv {
  const AppEnv({
    required this.appName,
    required this.flavor,
    required this.apiBaseUrl,
    required this.connectTimeoutMs,
    required this.receiveTimeoutMs,
    required this.sendTimeoutMs,
    required this.enableVerboseLogs,
    required this.enableSentry,
    required this.enableCrashlytics,
    required this.sentryDsn,
    required this.sentryTracesSampleRate,
  });

  factory AppEnv.fromEnvironment() {
    const flavorName = String.fromEnvironment(
      'FLAVOR',
      defaultValue: '$defaultFlavor',
    );

    return AppEnv(
      appName: const String.fromEnvironment(
        'APP_NAME',
        defaultValue: '${resolved.appName}',
      ),
      flavor: FlavorX.fromName(flavorName),
      apiBaseUrl: const String.fromEnvironment(
        'API_BASE_URL',
        defaultValue: 'https://api.example.com',
      ),
      connectTimeoutMs: const int.fromEnvironment(
        'CONNECT_TIMEOUT_MS',
        defaultValue: 15000,
      ),
      receiveTimeoutMs: const int.fromEnvironment(
        'RECEIVE_TIMEOUT_MS',
        defaultValue: 15000,
      ),
      sendTimeoutMs: const int.fromEnvironment(
        'SEND_TIMEOUT_MS',
        defaultValue: 15000,
      ),
      enableVerboseLogs: const bool.fromEnvironment(
        'ENABLE_VERBOSE_LOGS',
        defaultValue: true,
      ),
      enableSentry: const bool.fromEnvironment(
        'ENABLE_SENTRY',
        defaultValue: $enableSentryDefault,
      ),
      enableCrashlytics: const bool.fromEnvironment(
        'ENABLE_CRASHLYTICS',
        defaultValue: $enableCrashlyticsDefault,
      ),
      sentryDsn: const String.fromEnvironment(
        'SENTRY_DSN',
        defaultValue: '',
      ),
      sentryTracesSampleRate: double.tryParse(
            const String.fromEnvironment(
              'SENTRY_TRACES_SAMPLE_RATE',
              defaultValue: '0.0',
            ),
          ) ??
          0.0,
    );
  }

  final String apiBaseUrl;
  final String appName;
  final int connectTimeoutMs;
  final bool enableCrashlytics;
  final bool enableSentry;
  final bool enableVerboseLogs;
  final Flavor flavor;
  final int receiveTimeoutMs;
  final String sentryDsn;
  final double sentryTracesSampleRate;
  final int sendTimeoutMs;

  String get flavorName => flavor.value;
}
''';
  }

  String _flavorDart(ResolvedGenerationConfig resolved) {
    final entries = resolved.config.flavors.join(', ');
    final valueCases = resolved.config.flavors
        .map(
          (flavor) => "      case Flavor.$flavor:\n        return '$flavor';",
        )
        .join('\n');
    final parseCases = resolved.config.flavors
        .map(
          (flavor) => "      case '$flavor':\n        return Flavor.$flavor;",
        )
        .join('\n');
    final defaultFlavor = resolved.config.flavors.first;

    return '''
enum Flavor { $entries }

extension FlavorX on Flavor {
  String get value {
    switch (this) {
$valueCases
    }
  }

  static Flavor fromName(String value) {
    switch (value.toLowerCase()) {
$parseCases
      default:
        return Flavor.$defaultFlavor;
    }
  }
}
''';
  }

  String _injectionDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import '${_packageImport(resolved, 'core/config/env.dart')}';
import '${_packageImport(resolved, 'core/di/injection.config.dart')}';

final GetIt getIt = GetIt.instance;

  @InjectableInit(preferRelativeImports: true)
  Future<GetIt> configureDependencies(AppEnv env) async {
  await getIt.reset();
  // Make the runtime environment available to generated modules
  getIt.registerSingleton<AppEnv>(env);
  // Delegate registrations to the generated code (extension `init`).
  await getIt.init(environment: env.flavorName);
  return getIt;
}
''';
  }

  String _monitoringModuleDart(ResolvedGenerationConfig resolved) {
    final imports = <String>[
      "import 'package:injectable/injectable.dart';",
      "import '${_packageImport(resolved, 'core/config/env.dart')}';",
      "import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';",
      "import '${_packageImport(resolved, 'core/logging/app_logger_impl.dart')}';",
      "import '${_packageImport(resolved, 'core/monitoring/app_monitor.dart')}';",
      "import '${_packageImport(resolved, 'core/monitoring/app_monitor_impl.dart')}';",
      if (resolved.config.enableSentry)
        "import '${_packageImport(resolved, 'core/monitoring/sentry_monitoring_service.dart')}';",
      if (resolved.config.enableCrashlytics)
        "import '${_packageImport(resolved, 'core/monitoring/crashlytics_monitoring_service.dart')}';",
    ];

    final appMonitorParameters = <String>[
      'AppLogger logger',
      if (resolved.config.enableSentry)
        'SentryMonitoringService sentryMonitoringService',
      if (resolved.config.enableCrashlytics)
        'CrashlyticsMonitoringService crashlyticsMonitoringService',
    ].join(', ');

    final appMonitorArguments = <String>[
      'logger',
      if (resolved.config.enableSentry) 'sentryMonitoringService',
      if (resolved.config.enableCrashlytics) 'crashlyticsMonitoringService',
    ].join(', ');

    return '''
${imports.join('\n')}

@module
abstract class MonitoringModule {
  @lazySingleton
  AppLogger appLogger() {
    return AppLoggerImpl(enableVerboseLogs: AppEnv.fromEnvironment().enableVerboseLogs);
  }

  @lazySingleton
  AppMonitor appMonitor($appMonitorParameters) {
    return AppMonitorImpl($appMonitorArguments);
  }
}
''';
  }

  String _serviceModuleDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';
import '${_packageImport(resolved, 'core/config/env.dart')}';
import '${_packageImport(resolved, 'core/lifecycle/app_lifecycle_manager.dart')}';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';
import '${_packageImport(resolved, 'core/monitoring/app_monitor.dart')}';
import '${_packageImport(resolved, 'core/network/dio_client.dart')}';
import '${_packageImport(resolved, 'core/network/interceptors/auth_interceptor.dart')}';
import '${_packageImport(resolved, 'core/network/interceptors/logging_interceptor.dart')}';
import '${_packageImport(resolved, 'core/network/interceptors/retry_interceptor.dart')}';
import '${_packageImport(resolved, 'core/network/network_config.dart')}';

@module
abstract class ServiceModule {
  @lazySingleton
  NetworkConfig networkConfig() {
    return NetworkConfig.fromEnv(AppEnv.fromEnvironment());
  }

  @lazySingleton
  Dio dio(
    NetworkConfig config,
    AuthInterceptor authInterceptor,
    LoggingInterceptor loggingInterceptor,
    RetryInterceptor retryInterceptor,
  ) {
    return DioClient.build(
      config: config,
      authInterceptor: authInterceptor,
      loggingInterceptor: loggingInterceptor,
      retryInterceptor: retryInterceptor,
    );
  }

  @lazySingleton
  AppLifecycleManager lifecycleManager(AppLogger logger, AppMonitor monitor) {
    return AppLifecycleManager(logger: logger, monitor: monitor);
  }
}
''';
  }

  String _storageModuleDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '${_packageImport(resolved, 'core/services/security/secure_storage_service.dart')}';
import '${_packageImport(resolved, 'core/network/services/token_storage.dart')}';
import '${_packageImport(resolved, 'core/network/services/token_provider.dart')}';

@module
abstract class StorageModule {
  @preResolve
  Future<SharedPreferences> sharedPreferences() {
    return SharedPreferences.getInstance();
  }

  @lazySingleton
  FlutterSecureStorage secureStorage() {
    return const FlutterSecureStorage();
  }

    @lazySingleton
    TokenStorage tokenStorage(SecureStorageService secureStorageService) {
      return SecureTokenStorage(secureStorageService);
    }

    @lazySingleton
    TokenProvider tokenProvider(TokenStorage tokenStorage) {
      return SecureTokenProvider(tokenStorage);
    }
}
''';
  }

  String _deviceInfoModuleDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:device_info_plus/device_info_plus.dart';
import 'package:injectable/injectable.dart';

@module
abstract class DeviceInfoModule {
  @lazySingleton
  DeviceInfoPlugin deviceInfoPlugin() {
    return DeviceInfoPlugin();
  }
}
''';
  }

  String _appFailureDart() {
    return '''
import 'package:equatable/equatable.dart';

class AppFailure extends Equatable {
  const AppFailure({
    required this.type,
    required this.message,
    this.statusCode,
    this.stackTrace,
  });

  factory AppFailure.auth(String message) {
    return AppFailure(type: 'auth', message: message);
  }

  factory AppFailure.network(String message, {int? statusCode}) {
    return AppFailure(
      type: 'network',
      message: message,
      statusCode: statusCode,
    );
  }

  factory AppFailure.unexpected(String message, {StackTrace? stackTrace}) {
    return AppFailure(
      type: 'unexpected',
      message: message,
      stackTrace: stackTrace,
    );
  }

  factory AppFailure.validation(String message) {
    return AppFailure(type: 'validation', message: message);
  }

  final String message;
  final StackTrace? stackTrace;
  final int? statusCode;
  final String type;

  @override
  List<Object?> get props => <Object?>[type, message, statusCode];
}
''';
  }

  String _globalErrorMapperDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/error/app_failure.dart')}';

class GlobalErrorMapper {
  const GlobalErrorMapper();

  AppFailure map(Object error, [StackTrace? stackTrace]) {
    if (error is AppFailure) {
      return error;
    }

    return AppFailure.unexpected(
      error.toString(),
      stackTrace: stackTrace,
    );
  }
}
''';
  }

  String _appHapticsDart() {
    return '''
import 'package:flutter/services.dart';

class AppHaptics {
  const AppHaptics();

  Future<void> selectionClick() {
    return HapticFeedback.selectionClick();
  }

  Future<void> lightImpact() {
    return HapticFeedback.lightImpact();
  }
}
''';
  }

  String _lifecycleManagerDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:flutter/widgets.dart';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';
import '${_packageImport(resolved, 'core/monitoring/app_monitor.dart')}';

class AppLifecycleManager with WidgetsBindingObserver {
  AppLifecycleManager({
    required AppLogger logger,
    required AppMonitor monitor,
  })  : _logger = logger,
        _monitor = monitor;

  final AppLogger _logger;
  final AppMonitor _monitor;
  bool _isInitialized = false;

  void initialize() {
    if (_isInitialized) {
      return;
    }

    WidgetsBinding.instance.addObserver(this);
    _isInitialized = true;
    _logger.info('Lifecycle manager initialized.');
  }

  void dispose() {
    if (!_isInitialized) {
      return;
    }

    WidgetsBinding.instance.removeObserver(this);
    _isInitialized = false;
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    _logger.debug('Lifecycle state changed to \$state.');
    _monitor.recordTrace('lifecycle:\${state.name}');
  }
}
''';
  }

  String _appLoggerDart() {
    return '''
abstract class AppLogger {
  void debug(String message);
  void info(String message);
  void warning(String message);
  void error(
    String message, {
    Object? error,
    StackTrace? stackTrace,
  });
}
''';
  }

  String _appLoggerImplDart() {
    return '''
import 'dart:developer' as developer;

import 'package:flutter/foundation.dart';

import 'app_logger.dart';

class AppLoggerImpl implements AppLogger {
  AppLoggerImpl({required bool enableVerboseLogs})
      : _enableVerboseLogs = enableVerboseLogs;

  final bool _enableVerboseLogs;

  @override
  void debug(String message) {
    if (_enableVerboseLogs || kDebugMode) {
      developer.log(message, name: 'debug');
    }
  }

  @override
  void info(String message) {
    developer.log(message, name: 'info');
  }

  @override
  void warning(String message) {
    developer.log(message, name: 'warning');
  }

  @override
  void error(
    String message, {
    Object? error,
    StackTrace? stackTrace,
  }) {
    developer.log(
      message,
      name: 'error',
      error: error,
      stackTrace: stackTrace,
    );
  }
}
''';
  }

  String _appMonitorDart() {
    return '''
abstract class AppMonitor {
  void recordError(Object error, {StackTrace? stackTrace});
  void recordTrace(String message);
}
''';
  }

  String _appMonitorImplDart(ResolvedGenerationConfig resolved) {
    final imports = <String>[
      if (resolved.config.enableSentry || resolved.config.enableCrashlytics)
        "import 'dart:async';",
      "import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';",
      if (resolved.config.enableSentry)
        "import '${_packageImport(resolved, 'core/monitoring/sentry_monitoring_service.dart')}';",
      if (resolved.config.enableCrashlytics)
        "import '${_packageImport(resolved, 'core/monitoring/crashlytics_monitoring_service.dart')}';",
    ];

    final constructorParameters = <String>[
      'this._logger',
      if (resolved.config.enableSentry) 'this._sentryMonitoringService',
      if (resolved.config.enableCrashlytics)
        'this._crashlyticsMonitoringService',
    ].join(', ');

    final fields = <String>[
      '  final AppLogger _logger;',
      if (resolved.config.enableSentry)
        '  final SentryMonitoringService _sentryMonitoringService;',
      if (resolved.config.enableCrashlytics)
        '  final CrashlyticsMonitoringService _crashlyticsMonitoringService;',
    ].join('\n');

    final recordErrorExtra = <String>[
      if (resolved.config.enableSentry)
        '    unawaited(_sentryMonitoringService.captureException(error, stackTrace: stackTrace));',
      if (resolved.config.enableCrashlytics)
        '    unawaited(_crashlyticsMonitoringService.recordError(error, stackTrace: stackTrace));',
    ].join('\n');

    final recordTraceExtra = <String>[
      if (resolved.config.enableSentry)
        '    unawaited(_sentryMonitoringService.addBreadcrumb(message));',
      if (resolved.config.enableCrashlytics)
        '    _crashlyticsMonitoringService.log(message);',
    ].join('\n');

    return '''
${imports.join('\n')}
import 'app_monitor.dart';

class AppMonitorImpl implements AppMonitor {
  AppMonitorImpl($constructorParameters);

$fields

  @override
  void recordError(Object error, {StackTrace? stackTrace}) {
    _logger.error(
      'Monitor captured an error.',
      error: error,
      stackTrace: stackTrace,
    );
$recordErrorExtra
  }

  @override
  void recordTrace(String message) {
    _logger.debug(message);
$recordTraceExtra
  }
}
''';
  }

  String _dioClientDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import '${_packageImport(resolved, 'core/network/interceptors/auth_interceptor.dart')}';
import '${_packageImport(resolved, 'core/network/interceptors/logging_interceptor.dart')}';
import '${_packageImport(resolved, 'core/network/interceptors/retry_interceptor.dart')}';
import '${_packageImport(resolved, 'core/network/network_config.dart')}';

class DioClient {
  const DioClient._();

  static Dio build({
    required NetworkConfig config,
    required AuthInterceptor authInterceptor,
    required LoggingInterceptor loggingInterceptor,
    required RetryInterceptor retryInterceptor,
  }) {
    final dio = Dio(
      BaseOptions(
        baseUrl: config.baseUrl,
        connectTimeout: Duration(milliseconds: config.connectTimeoutMs),
        receiveTimeout: Duration(milliseconds: config.receiveTimeoutMs),
        sendTimeout: Duration(milliseconds: config.sendTimeoutMs),
        headers: config.defaultHeaders,
      ),
    );

    dio.interceptors.addAll(<Interceptor>[
      authInterceptor,
      loggingInterceptor,
      retryInterceptor,
    ]);

    return dio;
  }
}
''';
  }

  String _networkConfigDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/config/env.dart')}';

class NetworkConfig {
  const NetworkConfig({
    required this.baseUrl,
    required this.connectTimeoutMs,
    required this.receiveTimeoutMs,
    required this.sendTimeoutMs,
    this.defaultHeaders = const <String, String>{
      'Accept': 'application/json',
    },
  });

  factory NetworkConfig.fromEnv(AppEnv env) {
    return NetworkConfig(
      baseUrl: env.apiBaseUrl,
      connectTimeoutMs: env.connectTimeoutMs,
      receiveTimeoutMs: env.receiveTimeoutMs,
      sendTimeoutMs: env.sendTimeoutMs,
    );
  }

  final String baseUrl;
  final int connectTimeoutMs;
  final Map<String, String> defaultHeaders;
  final int receiveTimeoutMs;
  final int sendTimeoutMs;
}
''';
  }

  String _networkConstantsDart() {
    return '''
class NetworkConstants {
  const NetworkConstants._();

  static const String authorizationHeader = 'Authorization';
  static const String bearerPrefix = 'Bearer';
  static const String contentTypeHeader = 'Content-Type';
}
''';
  }

  String _authInterceptorDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';
import '${_packageImport(resolved, 'core/network/network_constants.dart')}';
import '${_packageImport(resolved, 'core/network/services/token_provider.dart')}';

@lazySingleton
class AuthInterceptor extends Interceptor {
  AuthInterceptor({
    required TokenProvider tokenProvider,
    required AppLogger logger,
  })  : _tokenProvider = tokenProvider,
        _logger = logger;

  final AppLogger _logger;
  final TokenProvider _tokenProvider;

  @override
  Future<void> onRequest(
    RequestOptions options,
    RequestInterceptorHandler handler,
  ) async {
    final requiresAuth = options.extra['requiresAuth'] == true;
    if (!requiresAuth) {
      handler.next(options);
      return;
    }

    final token = await _tokenProvider.readToken();
    if (token == null || token.isEmpty) {
      _logger.warning('Authenticated request missing a token for \${options.path}.');
      handler.reject(
        DioException(
          requestOptions: options,
          error: StateError('Missing authentication token.'),
          type: DioExceptionType.unknown,
        ),
      );
      return;
    }

    options.headers[NetworkConstants.authorizationHeader] =
        '\${NetworkConstants.bearerPrefix} \$token';
    handler.next(options);
  }
}
''';
  }

  String _loggingInterceptorDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';
import '${_packageImport(resolved, 'core/config/env.dart')}';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';
import '${_packageImport(resolved, 'core/network/network_constants.dart')}';

@lazySingleton
class LoggingInterceptor extends Interceptor {
  LoggingInterceptor({
    required AppLogger logger,
  })  : _logger = logger,
        _isVerbose = AppEnv.fromEnvironment().enableVerboseLogs;

  final bool _isVerbose;
  final AppLogger _logger;

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    options.extra['startedAt'] = DateTime.now();
    if (_isVerbose) {
      _logger.info(
        'HTTP \${options.method} \${options.uri} headers=\${_sanitizeHeaders(options.headers)}',
      );
    }
    handler.next(options);
  }

  @override
  void onResponse(Response<dynamic> response, ResponseInterceptorHandler handler) {
    final startedAt = response.requestOptions.extra['startedAt'] as DateTime?;
    final durationMs = startedAt == null
        ? null
        : DateTime.now().difference(startedAt).inMilliseconds;
    _logger.info(
      'HTTP \${response.requestOptions.method} \${response.requestOptions.uri} -> \${response.statusCode} in \${durationMs ?? '-'}ms',
    );
    handler.next(response);
  }

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    final startedAt = err.requestOptions.extra['startedAt'] as DateTime?;
    final durationMs = startedAt == null
        ? null
        : DateTime.now().difference(startedAt).inMilliseconds;
    _logger.error(
      'HTTP \${err.requestOptions.method} \${err.requestOptions.uri} failed in \${durationMs ?? '-'}ms',
      error: err,
      stackTrace: err.stackTrace,
    );
    handler.next(err);
  }

  Map<String, dynamic> _sanitizeHeaders(Map<String, dynamic> headers) {
    final safe = <String, dynamic>{};
    headers.forEach((key, value) {
      final normalizedKey = key.toLowerCase();
      if (normalizedKey == NetworkConstants.authorizationHeader.toLowerCase() ||
          normalizedKey == 'cookie') {
        safe[key] = '***';
        return;
      }
      safe[key] = value;
    });
    return safe;
  }
}
''';
  }

  String _retryInterceptorDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';

@lazySingleton
class RetryInterceptor extends Interceptor {
  RetryInterceptor({
    required AppLogger logger,
    this.enabled = false,
  }) : _logger = logger;

  final bool enabled;
  final AppLogger _logger;

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    if (enabled &&
        err.requestOptions.method.toUpperCase() == 'GET' &&
        _isRetryable(err)) {
      _logger.warning(
        'Retry candidate detected for \${err.requestOptions.uri}, but phase 1 keeps retries conservative and opt-in.',
      );
    }

    handler.next(err);
  }

  bool _isRetryable(DioException error) {
    return error.type == DioExceptionType.connectionError ||
        error.type == DioExceptionType.connectionTimeout ||
        error.type == DioExceptionType.receiveTimeout;
  }
}
''';
  }

  String _apiErrorResponseDart() {
    return '''
import 'package:equatable/equatable.dart';

class ApiErrorResponse extends Equatable {
  const ApiErrorResponse({
    required this.message,
    this.code,
    this.statusCode,
  });

  factory ApiErrorResponse.fromMap(Map<String, dynamic> map) {
    return ApiErrorResponse(
      message: map['message']?.toString() ?? 'Request failed.',
      code: map['code']?.toString(),
      statusCode: map['statusCode'] as int?,
    );
  }

  final String? code;
  final String message;
  final int? statusCode;

  @override
  List<Object?> get props => <Object?>[code, message, statusCode];
}
''';
  }

  String _requestOptionsDart() {
    return '''
import 'package:equatable/equatable.dart';

class ApiRequestOptions extends Equatable {
  const ApiRequestOptions({
    required this.path,
    this.queryParameters,
    this.headers,
    this.requiresAuth = false,
  });

  final Map<String, dynamic>? headers;
  final String path;
  final Map<String, dynamic>? queryParameters;
  final bool requiresAuth;

  @override
  List<Object?> get props => <Object?>[
        path,
        queryParameters,
        headers,
        requiresAuth,
      ];
}
''';
  }

  String _apiClientDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import '${_packageImport(resolved, 'core/utils/result.dart')}';

abstract class ApiClient {
  Future<Result<Map<String, dynamic>>> get(
    String path, {
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  });

  Future<Result<Map<String, dynamic>>> post(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  });

  Future<Result<Map<String, dynamic>>> patch(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  });

  Future<Result<Map<String, dynamic>>> delete(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  });

  Future<Result<String>> download(
    String url, {
    required String savePath,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
    void Function(int received, int total)? onReceiveProgress,
  });

  Future<Result<Map<String, dynamic>>> postMultipart(
    String path, {
    required Map<String, dynamic> fields,
    List<MultipartFile>? files,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  });
}
''';
  }

  String _apiClientImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:dio/dio.dart';
import '${_packageImport(resolved, 'core/error/app_failure.dart')}';
import '${_packageImport(resolved, 'core/error/global_error_mapper.dart')}';
import '${_packageImport(resolved, 'core/network/network_config.dart')}';
import '${_packageImport(resolved, 'core/network/services/api_client.dart')}';
import '${_packageImport(resolved, 'core/network/services/token_provider.dart')}';
import '${_packageImport(resolved, 'core/network/utils/network_error_mapper.dart')}';
import '${_packageImport(resolved, 'core/network/utils/request_validator.dart')}';
import '${_packageImport(resolved, 'core/utils/result.dart')}';

class ApiClientImpl implements ApiClient {
  ApiClientImpl({
    required Dio dio,
    required TokenProvider tokenProvider,
    required NetworkConfig networkConfig,
    required NetworkErrorMapper networkErrorMapper,
    required GlobalErrorMapper globalErrorMapper,
    required RequestValidator requestValidator,
  })  : _dio = dio,
        _tokenProvider = tokenProvider,
        _networkConfig = networkConfig,
        _networkErrorMapper = networkErrorMapper,
        _globalErrorMapper = globalErrorMapper,
        _requestValidator = requestValidator;

  final Dio _dio;
  final GlobalErrorMapper _globalErrorMapper;
  final NetworkConfig _networkConfig;
  final NetworkErrorMapper _networkErrorMapper;
  final RequestValidator _requestValidator;
  final TokenProvider _tokenProvider;

  @override
  Future<Result<Map<String, dynamic>>> get(
    String path, {
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  }) {
    return _request(
      'GET',
      path,
      queryParameters: queryParameters,
      headers: headers,
      requiresAuth: requiresAuth,
    );
  }

  @override
  Future<Result<Map<String, dynamic>>> post(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  }) {
    return _request(
      'POST',
      path,
      data: data,
      queryParameters: queryParameters,
      headers: headers,
      requiresAuth: requiresAuth,
    );
  }

  @override
  Future<Result<Map<String, dynamic>>> patch(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  }) {
    return _request(
      'PATCH',
      path,
      data: data,
      queryParameters: queryParameters,
      headers: headers,
      requiresAuth: requiresAuth,
    );
  }

  @override
  Future<Result<Map<String, dynamic>>> delete(
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  }) {
    return _request(
      'DELETE',
      path,
      data: data,
      queryParameters: queryParameters,
      headers: headers,
      requiresAuth: requiresAuth,
    );
  }

  @override
  Future<Result<String>> download(
    String url, {
    required String savePath,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
    void Function(int received, int total)? onReceiveProgress,
  }) async {
    final failure = await _validateRequest(
      path: url,
      headers: headers,
      requiresAuth: requiresAuth,
    );
    if (failure != null) {
      return Result.failure(failure);
    }

    try {
      await _dio.download(
        url,
        savePath,
        queryParameters: queryParameters,
        options: Options(
          headers: _sanitizeHeaders(headers),
          extra: <String, Object?>{'requiresAuth': requiresAuth},
        ),
        onReceiveProgress: onReceiveProgress,
      );
      return Result.success(savePath);
    } on DioException catch (error, stackTrace) {
      return Result.failure(_networkErrorMapper.map(error, stackTrace));
    } catch (error, stackTrace) {
      return Result.failure(_globalErrorMapper.map(error, stackTrace));
    }
  }

  @override
  Future<Result<Map<String, dynamic>>> postMultipart(
    String path, {
    required Map<String, dynamic> fields,
    List<MultipartFile>? files,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  }) async {
    final failure = await _validateRequest(
      path: path,
      headers: headers,
      requiresAuth: requiresAuth,
    );
    if (failure != null) {
      return Result.failure(failure);
    }

    final payload = <String, dynamic>{...fields};
    if (files != null && files.isNotEmpty) {
      payload['files'] = files.length == 1 ? files.first : files;
    }

    try {
      final response = await _dio.post<dynamic>(
        path,
        data: FormData.fromMap(payload),
        options: Options(
          headers: _sanitizeHeaders(headers),
          extra: <String, Object?>{'requiresAuth': requiresAuth},
        ),
      );
      return Result.success(_normalizeResponse(response.data));
    } on DioException catch (error, stackTrace) {
      return Result.failure(_networkErrorMapper.map(error, stackTrace));
    } catch (error, stackTrace) {
      return Result.failure(_globalErrorMapper.map(error, stackTrace));
    }
  }

  Future<Result<Map<String, dynamic>>> _request(
    String method,
    String path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? headers,
    bool requiresAuth = false,
  }) async {
    final failure = await _validateRequest(
      path: path,
      headers: headers,
      requiresAuth: requiresAuth,
    );
    if (failure != null) {
      return Result.failure(failure);
    }

    try {
      final response = await _dio.request<dynamic>(
        path,
        data: data,
        queryParameters: queryParameters,
        options: Options(
          method: method,
          headers: _sanitizeHeaders(headers),
          extra: <String, Object?>{'requiresAuth': requiresAuth},
        ),
      );
      return Result.success(_normalizeResponse(response.data));
    } on DioException catch (error, stackTrace) {
      return Result.failure(_networkErrorMapper.map(error, stackTrace));
    } catch (error, stackTrace) {
      return Result.failure(_globalErrorMapper.map(error, stackTrace));
    }
  }

  Map<String, dynamic> _normalizeResponse(Object? data) {
    if (data == null) {
      return const <String, dynamic>{};
    }
    if (data is Map<String, dynamic>) {
      return data;
    }
    return <String, dynamic>{'data': data};
  }

  Map<String, dynamic>? _sanitizeHeaders(Map<String, dynamic>? headers) {
    if (headers == null) {
      return null;
    }

    return Map<String, dynamic>.fromEntries(
      headers.entries.where(
        (entry) => entry.key.trim().isNotEmpty && entry.value != null,
      ),
    );
  }

  Future<AppFailure?> _validateRequest({
    required String path,
    Map<String, dynamic>? headers,
    required bool requiresAuth,
  }) async {
    final pathFailure = _requestValidator.validatePath(path);
    if (pathFailure != null) {
      return pathFailure;
    }

    final baseUrlFailure = _requestValidator.validateBaseUrl(_networkConfig.baseUrl);
    if (baseUrlFailure != null) {
      return baseUrlFailure;
    }

    final headerFailure = _requestValidator.validateHeaders(headers);
    if (headerFailure != null) {
      return headerFailure;
    }

    if (!requiresAuth) {
      return null;
    }

    final token = await _tokenProvider.readToken();
    if (token == null || token.isEmpty) {
      return AppFailure.auth('Authenticated request attempted without a token.');
    }

    return null;
  }
}
''';
  }

  String _tokenProviderDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/network/services/token_storage.dart')}';

abstract class TokenProvider {
  Future<String?> readToken();
}

class SecureTokenProvider implements TokenProvider {
  SecureTokenProvider(this._tokenStorage);

  final TokenStorage _tokenStorage;

  @override
  Future<String?> readToken() {
    return _tokenStorage.readAccessToken();
  }
}
''';
  }

  String _tokenStorageDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/services/security/secure_storage_service.dart')}';
import '${_packageImport(resolved, 'shared/constants/session_constants.dart')}';

abstract class TokenStorage {
  Future<void> clearAccessToken();
  Future<String?> readAccessToken();
  Future<void> writeAccessToken(String token);
}

class SecureTokenStorage implements TokenStorage {
  SecureTokenStorage(this._storageService);

  final SecureStorageService _storageService;

  @override
  Future<void> clearAccessToken() {
    return _storageService.delete(SessionConstants.accessTokenKey);
  }

  @override
  Future<String?> readAccessToken() {
    return _storageService.read(SessionConstants.accessTokenKey);
  }

  @override
  Future<void> writeAccessToken(String token) {
    return _storageService.write(SessionConstants.accessTokenKey, token);
  }
}
''';
  }

  String _multipartBuilderDart() {
    return '''
import 'package:dio/dio.dart';
import 'package:http_parser/http_parser.dart';

class MultipartInput {
  const MultipartInput({
    required this.field,
    required this.filePath,
    this.fileName,
    this.contentType,
  });

  final MediaType? contentType;
  final String field;
  final String? fileName;
  final String filePath;
}

class MultipartBuilder {
  const MultipartBuilder._();

  static Future<FormData> build({
    required Map<String, dynamic> fields,
    List<MultipartInput> files = const <MultipartInput>[],
  }) async {
    final formData = FormData.fromMap(<String, dynamic>{...fields});

    for (final file in files) {
      formData.files.add(
        MapEntry<String, MultipartFile>(
          file.field,
          await MultipartFile.fromFile(
            file.filePath,
            filename: file.fileName ?? _fallbackFileName(file.filePath),
            contentType: file.contentType,
          ),
        ),
      );
    }

    return formData;
  }

  static String _fallbackFileName(String filePath) {
    final normalizedPath = filePath.replaceAll('\\\\', '/');
    final segments = normalizedPath.split('/');
    return segments.isEmpty ? 'upload.bin' : segments.last;
  }
}
''';
  }

  String _networkErrorMapperDart() {
    return '''
import 'package:dio/dio.dart';
import '../../error/app_failure.dart';

class NetworkErrorMapper {
  const NetworkErrorMapper();

  AppFailure map(DioException error, [StackTrace? stackTrace]) {
    switch (error.type) {
      case DioExceptionType.connectionTimeout:
      case DioExceptionType.receiveTimeout:
      case DioExceptionType.sendTimeout:
        return AppFailure.network('The network request timed out.');
      case DioExceptionType.connectionError:
        return AppFailure.network('Unable to reach the server.');
      case DioExceptionType.badResponse:
        return AppFailure.network(
          'The server returned an error.',
          statusCode: error.response?.statusCode,
        );
      case DioExceptionType.cancel:
        return AppFailure.network('The request was cancelled.');
      case DioExceptionType.badCertificate:
      case DioExceptionType.unknown:
        return AppFailure.unexpected(
          error.message ?? 'An unexpected network error occurred.',
          stackTrace: stackTrace,
        );
    }
  }
}
''';
  }

  String _requestValidatorDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/error/app_failure.dart')}';
import '${_packageImport(resolved, 'core/network/utils/multipart_builder.dart')}';

class RequestValidator {
  const RequestValidator();

  AppFailure? validateBaseUrl(String baseUrl) {
    if (baseUrl.trim().isEmpty) {
      return AppFailure.validation('API base URL cannot be empty.');
    }

    final uri = Uri.tryParse(baseUrl);
    if (uri == null || !uri.hasScheme) {
      return AppFailure.validation('API base URL must be a valid URI.');
    }

    return null;
  }

  AppFailure? validateHeaders(Map<String, dynamic>? headers) {
    if (headers == null) {
      return null;
    }

    for (final entry in headers.entries) {
      if (entry.key.trim().isEmpty || entry.value == null) {
        return AppFailure.validation('Headers must have non-empty keys and values.');
      }
    }

    return null;
  }

  Future<AppFailure?> validateMultipartFiles(List<MultipartInput> files) {
    for (final file in files) {
      if (file.filePath.trim().isEmpty) {
        return Future<AppFailure?>.value(AppFailure.validation(
          'Multipart file path cannot be empty.',
        ));
      }
    }

    return Future<AppFailure?>.value(null);
  }

  AppFailure? validatePath(String path) {
    if (path.trim().isEmpty) {
      return AppFailure.validation('Request path cannot be empty.');
    }
    return null;
  }
}
''';
  }

  String _appPreferencesDart() {
    return '''
import 'package:shared_preferences/shared_preferences.dart';

abstract class AppPreferences {
  bool? readBool(String key);
  int? readInt(String key);
  String? readString(String key);

  Future<bool> remove(String key);
  Future<bool> writeBool(String key, bool value);
  Future<bool> writeInt(String key, int value);
  Future<bool> writeString(String key, String value);
}
''';
  }

  String _appPreferencesImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '${_packageImport(resolved, 'core/services/preferences/app_preferences.dart')}';

@LazySingleton(as: AppPreferences)
class AppPreferencesImpl implements AppPreferences {
  AppPreferencesImpl(this._sharedPreferences);

  final SharedPreferences _sharedPreferences;

  @override
  bool? readBool(String key) => _sharedPreferences.getBool(key);

  @override
  int? readInt(String key) => _sharedPreferences.getInt(key);

  @override
  String? readString(String key) => _sharedPreferences.getString(key);

  @override
  Future<bool> remove(String key) => _sharedPreferences.remove(key);

  @override
  Future<bool> writeBool(String key, bool value) {
    return _sharedPreferences.setBool(key, value);
  }

  @override
  Future<bool> writeInt(String key, int value) {
    return _sharedPreferences.setInt(key, value);
  }

  @override
  Future<bool> writeString(String key, String value) {
    return _sharedPreferences.setString(key, value);
  }
}
''';
  }

  String _secureStorageServiceDart() {
    return '''
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

abstract class SecureStorageService {
  Future<void> delete(String key);

  Future<String?> read(String key);

  Future<void> write(String key, String value);
}
''';
  }

  String _secureStorageServiceImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:injectable/injectable.dart';
import '${_packageImport(resolved, 'core/services/security/secure_storage_service.dart')}';

@LazySingleton(as: SecureStorageService)
class SecureStorageServiceImpl implements SecureStorageService {
  SecureStorageServiceImpl(this._storage);

  final FlutterSecureStorage _storage;

  @override
  Future<void> delete(String key) {
    return _storage.delete(key: key);
  }

  @override
  Future<String?> read(String key) {
    return _storage.read(key: key);
  }

  @override
  Future<void> write(String key, String value) {
    return _storage.write(key: key, value: value);
  }
}
''';
  }

  String _resultDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/error/app_failure.dart')}';

sealed class Result<T> {
  const Result();

  factory Result.failure(AppFailure failure) = FailureResult<T>;
  factory Result.success(T data) = SuccessResult<T>;

  AppFailure? get failureOrNull => switch (this) {
        FailureResult<T>(:final failure) => failure,
        _ => null,
      };

  bool get isFailure => this is FailureResult<T>;
  bool get isSuccess => this is SuccessResult<T>;

  T? get dataOrNull => switch (this) {
        SuccessResult<T>(:final data) => data,
        _ => null,
      };
}

class SuccessResult<T> extends Result<T> {
  const SuccessResult(this.data);

  final T data;
}

class FailureResult<T> extends Result<T> {
  const FailureResult(this.failure);

  final AppFailure failure;
}
''';
  }

  String _sentryMonitoringServiceDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:sentry_flutter/sentry_flutter.dart';
import 'package:injectable/injectable.dart';

import '${_packageImport(resolved, 'core/config/env.dart')}';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';

@lazySingleton
class SentryMonitoringService {
  SentryMonitoringService({required AppLogger logger}) : _logger = logger;

  final AppLogger _logger;

  Future<void> addBreadcrumb(String message) {
    return Sentry.addBreadcrumb(
      Breadcrumb(
        category: 'app.lifecycle',
        message: message,
      ),
    );
  }

  Future<SentryId> captureException(
    Object error, {
    StackTrace? stackTrace,
  }) {
    return Sentry.captureException(error, stackTrace: stackTrace);
  }

  Future<void> initialize({
    required AppEnv env,
    required Future<void> Function() appRunner,
  }) async {
    if (!env.enableSentry || env.sentryDsn.trim().isEmpty) {
      _logger.info('Sentry is disabled or missing a DSN.');
      await appRunner();
      return;
    }

    await SentryFlutter.init(
      (options) {
        options.dsn = env.sentryDsn;
        options.environment = env.flavorName;
        options.enableLogs = env.enableVerboseLogs;
        options.tracesSampleRate = env.sentryTracesSampleRate;
      },
      appRunner: appRunner,
    );
  }
}
''';
  }

  String _crashlyticsMonitoringServiceDart(ResolvedGenerationConfig resolved) {
    return '''
import 'dart:async';

import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:injectable/injectable.dart';

import '${_packageImport(resolved, 'core/config/env.dart')}';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';

@lazySingleton
class CrashlyticsMonitoringService {
  CrashlyticsMonitoringService({required AppLogger logger}) : _logger = logger;

  final AppLogger _logger;

  Future<void> initialize(AppEnv env) async {
    final crashlytics = FirebaseCrashlytics.instance;
    await crashlytics.setCrashlyticsCollectionEnabled(env.enableCrashlytics);
    if (!env.enableCrashlytics) {
      _logger.info('Crashlytics collection is disabled.');
      return;
    }

    await crashlytics.setCustomKey('app_name', env.appName);
    await crashlytics.setCustomKey('flavor', env.flavorName);

    final previousFlutterOnError = FlutterError.onError;
    FlutterError.onError = (details) {
      previousFlutterOnError?.call(details);
      crashlytics.recordFlutterFatalError(details);
    };

    final previousPlatformOnError = PlatformDispatcher.instance.onError;
    PlatformDispatcher.instance.onError = (error, stackTrace) {
      unawaited(crashlytics.recordError(error, stackTrace, fatal: true));
      previousPlatformOnError?.call(error, stackTrace);
      return true;
    };
  }

  void log(String message) {
    FirebaseCrashlytics.instance.log(message);
  }

  Future<void> recordError(
    Object error, {
    StackTrace? stackTrace,
    bool fatal = false,
  }) {
    return FirebaseCrashlytics.instance.recordError(
      error,
      stackTrace ?? StackTrace.current,
      fatal: fatal,
    );
  }
}
''';
  }

  String _firebaseFirestoreServiceDart(ResolvedGenerationConfig resolved) {
    return '''
import '${_packageImport(resolved, 'core/utils/result.dart')}';

abstract class FirebaseFirestoreService {
  Future<Result<void>> createDocument({
    required String collection,
    required String id,
    required Map<String, dynamic> data,
  });

  Future<void> upsertDocument({
    required String collection,
    required String id,
    required Map<String, dynamic> data,
  });

  Future<Map<String, dynamic>?> getDocument({
    required String collection,
    required String id,
  });

  Future<List<Map<String, dynamic>>> getDocuments({
    required String collection,
    String? orderBy,
    bool descending = false,
    int? limit,
  });

  Future<void> updateDocument({
    required String collection,
    required String id,
    required Map<String, dynamic> data,
  });

  Future<void> deleteDocument({
    required String collection,
    required String id,
  });
}
''';
  }

  String _firebaseFirestoreServiceImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:injectable/injectable.dart';

import '${_packageImport(resolved, 'core/error/app_failure.dart')}';
import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';
import '${_packageImport(resolved, 'core/services/firebase/firestore/firebase_firestore_service.dart')}';
import '${_packageImport(resolved, 'core/utils/result.dart')}';

@LazySingleton(as: FirebaseFirestoreService)
class FirebaseFirestoreServiceImpl implements FirebaseFirestoreService {
  FirebaseFirestoreServiceImpl({
    required AppLogger logger,
  })  : _logger = logger,
        _firestore = FirebaseFirestore.instance;

  final FirebaseFirestore _firestore;
  final AppLogger _logger;

  @override
  Future<Result<void>> createDocument({
    required String collection,
    required String id,
    required Map<String, dynamic> data,
  }) async {
    try {
      final reference = _documentReference(collection: collection, id: id);
      final document = await reference.get();
      if (document.exists) {
        return Result.failure(
          AppFailure.validation(
            'Document "\$id" already exists in collection "\$collection".',
          ),
        );
      }

      await reference.set(data);
      return Result<void>.success(null);
    } catch (error, stackTrace) {
      _logger.error(
        'Failed to create Firestore document \$collection/\$id.',
        error: error,
        stackTrace: stackTrace,
      );
      return Result.failure(
        AppFailure.unexpected(
          error.toString(),
          stackTrace: stackTrace,
        ),
      );
    }
  }

  @override
  Future<void> upsertDocument({
    required String collection,
    required String id,
    required Map<String, dynamic> data,
  }) async {
    await _documentReference(collection: collection, id: id).set(
      data,
      SetOptions(merge: true),
    );
  }

  @override
  Future<Map<String, dynamic>?> getDocument({
    required String collection,
    required String id,
  }) async {
    final snapshot = await _documentReference(collection: collection, id: id).get();
    return snapshot.data();
  }

  @override
  Future<List<Map<String, dynamic>>> getDocuments({
    required String collection,
    String? orderBy,
    bool descending = false,
    int? limit,
  }) async {
    Query<Map<String, dynamic>> query = _collectionReference(collection);
    if (orderBy != null && orderBy.trim().isNotEmpty) {
      query = query.orderBy(orderBy, descending: descending);
    }
    if (limit != null && limit > 0) {
      query = query.limit(limit);
    }

    final snapshot = await query.get();
    return snapshot.docs.map((document) => document.data()).toList();
  }

  @override
  Future<void> updateDocument({
    required String collection,
    required String id,
    required Map<String, dynamic> data,
  }) {
    return _documentReference(collection: collection, id: id).update(data);
  }

  @override
  Future<void> deleteDocument({
    required String collection,
    required String id,
  }) {
    return _documentReference(collection: collection, id: id).delete();
  }

  CollectionReference<Map<String, dynamic>> _collectionReference(String collection) {
    return _firestore.collection(collection);
  }

  DocumentReference<Map<String, dynamic>> _documentReference({
    required String collection,
    required String id,
  }) {
    return _collectionReference(collection).doc(id);
  }
  }
''';
  }

  String _remoteConfigServiceDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:firebase_remote_config/firebase_remote_config.dart';

abstract class FirebaseRemoteConfigService {
  Future<void> initialize({
    Map<String, Object> defaults = const <String, Object>{},
  });

  Future<bool> fetchAndActivate();

  Future<void> setDefaults(Map<String, Object> defaults);

  String getString(String key);

  bool getBool(String key);

  int getInt(String key);

  double getDouble(String key);

  FirebaseRemoteConfig get instance;
}
''';
  }

  String _remoteConfigServiceImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:firebase_remote_config/firebase_remote_config.dart';
import 'package:injectable/injectable.dart';

import '${_packageImport(resolved, 'core/logging/app_logger.dart')}';
import '${_packageImport(resolved, 'core/services/firebase/remote_config/firebase_remote_config_service.dart')}';

@LazySingleton(as: FirebaseRemoteConfigService)
class FirebaseRemoteConfigServiceImpl implements FirebaseRemoteConfigService {
  FirebaseRemoteConfigServiceImpl({
    required AppLogger logger,
  })  : _logger = logger,
        _remoteConfig = FirebaseRemoteConfig.instance;

  final AppLogger _logger;
  final FirebaseRemoteConfig _remoteConfig;

  @override
  FirebaseRemoteConfig get instance => _remoteConfig;

  @override
  Future<void> initialize({
    Map<String, Object> defaults = const <String, Object>{},
  }) async {
    await setDefaults(defaults);
    await fetchAndActivate();
    _logger.info('Remote config initialized.');
  }

  @override
  Future<bool> fetchAndActivate() {
    return _remoteConfig.fetchAndActivate();
  }

  @override
  Future<void> setDefaults(Map<String, Object> defaults) {
    return _remoteConfig.setDefaults(defaults);
  }

  @override
  String getString(String key) {
    return _remoteConfig.getString(key);
  }

  @override
  bool getBool(String key) {
    return _remoteConfig.getBool(key);
  }

  @override
  int getInt(String key) {
    return _remoteConfig.getInt(key);
  }

  @override
  double getDouble(String key) {
    return _remoteConfig.getDouble(key);
  }
}
''';
  }

  String _sentryPropertiesExample() {
    return '''
defaults.url=https://sentry.io/
defaults.org=your-sentry-org
defaults.project=your-sentry-project
auth.token=your-sentry-auth-token
''';
  }

  String _deviceInfoServiceDart() {
    return '''
import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/foundation.dart';

class AppDeviceInfoService {
  AppDeviceInfoService(this._deviceInfoPlugin);

  final DeviceInfoPlugin _deviceInfoPlugin;

  Future<Map<String, String>> snapshot() async {
    if (kIsWeb) {
      final info = await _deviceInfoPlugin.webBrowserInfo;
      return <String, String>{
        'platform': 'web',
        'browserName': info.browserName.name,
        'userAgent': info.userAgent ?? '',
      };
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      final info = await _deviceInfoPlugin.androidInfo;
      return <String, String>{
        'platform': 'android',
        'model': info.model,
        'manufacturer': info.manufacturer,
      };
      case TargetPlatform.iOS:
      final info = await _deviceInfoPlugin.iosInfo;
      return <String, String>{
        'platform': 'ios',
        'model': info.model,
        'systemVersion': info.systemVersion,
      };
      default:
        return <String, String>{
          'platform': defaultTargetPlatform.name,
        };
    }
  }
}
''';
  }

  String _hiveCacheServiceDart() {
    return '''
import 'package:hive_flutter/hive_flutter.dart';

abstract class HiveCacheService {
  Future<void> initialize();

  Future<Box<T>> openBox<T>(String name);

  Future<void> create<T>(String boxName, String key, T value);

  Future<T?> read<T>(String boxName, String key, {T? defaultValue});

  Future<Map<String, T>> readAll<T>(String boxName);

  Future<void> update<T>(String boxName, String key, T value);

  Future<bool> contains(String boxName, String key);

  Future<void> delete(String boxName, String key);

  Future<void> clear(String boxName);

  Future<void> closeAll();
}
''';
  }

  String _hiveCacheServiceImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:injectable/injectable.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '${_packageImport(resolved, 'core/services/cache/hive_cache_service.dart')}';

@LazySingleton(as: HiveCacheService)
class HiveCacheServiceImpl implements HiveCacheService {
  final Map<String, Box<dynamic>> _openBoxes = <String, Box<dynamic>>{};
  bool _initialized = false;

  @override
  Future<void> initialize() async {
    if (_initialized) {
      return;
    }
    await Hive.initFlutter();
    _initialized = true;
  }

  @override
  Future<Box<T>> openBox<T>(String name) async {
    await initialize();

    final existingBox = _openBoxes[name];
    if (existingBox != null && existingBox.isOpen) {
      return existingBox as Box<T>;
    }

    final box = await Hive.openBox<T>(name);
    _openBoxes[name] = box;
    return box;
  }

  @override
  Future<void> create<T>(String boxName, String key, T value) async {
    final box = await openBox<T>(boxName);
    if (box.containsKey(key)) {
      throw StateError('An entry already exists for "\$key" in "\$boxName".');
    }

    await box.put(key, value);
  }

  @override
  Future<T?> read<T>(String boxName, String key, {T? defaultValue}) async {
    final box = await openBox<T>(boxName);
    return box.get(key, defaultValue: defaultValue);
  }

  @override
  Future<Map<String, T>> readAll<T>(String boxName) async {
    final box = await openBox<T>(boxName);
    return Map<String, T>.fromEntries(
      box.keys.map(
        (key) => MapEntry(key.toString(), box.get(key) as T),
      ),
    );
  }

  @override
  Future<void> update<T>(String boxName, String key, T value) async {
    final box = await openBox<T>(boxName);
    if (!box.containsKey(key)) {
      throw StateError('No entry found for "\$key" in "\$boxName".');
    }

    await box.put(key, value);
  }

  @override
  Future<bool> contains(String boxName, String key) async {
    final box = await openBox<dynamic>(boxName);
    return box.containsKey(key);
  }

  @override
  Future<void> delete(String boxName, String key) async {
    final box = await openBox<dynamic>(boxName);
    await box.delete(key);
  }

  @override
  Future<void> clear(String boxName) async {
    final box = await openBox<dynamic>(boxName);
    await box.clear();
  }

  @override
  Future<void> closeAll() async {
    for (final box in _openBoxes.values) {
      if (box.isOpen) {
        await box.close();
      }
    }
    _openBoxes.clear();
    _initialized = false;
  }
}
''';
  }

  String _databaseServiceDart() {
    return '''
import 'package:sqflite/sqflite.dart';

abstract class AppDatabaseService {
  Future<Database> open({
    String fileName = 'app.db',
    int version = 1,
    OnDatabaseConfigureFn? onConfigure,
    OnDatabaseCreateFn? onCreate,
    OnDatabaseVersionChangeFn? onUpgrade,
    OnDatabaseVersionChangeFn? onDowngrade,
    OnDatabaseOpenFn? onOpen,
  });

  Future<int> create(
    String table,
    Map<String, Object?> values, {
    ConflictAlgorithm conflictAlgorithm = ConflictAlgorithm.abort,
  });

  Future<List<Map<String, Object?>>> read(
    String table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  });

  Future<Map<String, Object?>?> readById(
    String table,
    Object id, {
    String idColumn = 'id',
    List<String>? columns,
  });

  Future<int> update(
    String table,
    Map<String, Object?> values, {
    String? where,
    List<Object?>? whereArgs,
    ConflictAlgorithm conflictAlgorithm = ConflictAlgorithm.abort,
  });

  Future<int> delete(
    String table, {
    String? where,
    List<Object?>? whereArgs,
  });

  Future<int> count(
    String table, {
    String? where,
    List<Object?>? whereArgs,
  });

  Future<T> transaction<T>(Future<T> Function(Transaction txn) action);

  Future<void> close();
}
''';
  }

  String _databaseServiceImplDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:injectable/injectable.dart';
import 'package:sqflite/sqflite.dart';
import '${_packageImport(resolved, 'core/services/database/app_database_service.dart')}';

@LazySingleton(as: AppDatabaseService)
class AppDatabaseServiceImpl implements AppDatabaseService {
  Database? _database;

  @override
  Future<Database> open({
    String fileName = 'app.db',
    int version = 1,
    OnDatabaseConfigureFn? onConfigure,
    OnDatabaseCreateFn? onCreate,
    OnDatabaseVersionChangeFn? onUpgrade,
    OnDatabaseVersionChangeFn? onDowngrade,
    OnDatabaseOpenFn? onOpen,
  }) async {
    if (_database != null) {
      return _database!;
    }

    final databasePath = await getDatabasesPath();
    _database = await openDatabase(
      '\$databasePath/\$fileName',
      version: version,
      onConfigure: onConfigure,
      onCreate: onCreate,
      onUpgrade: onUpgrade,
      onDowngrade: onDowngrade,
      onOpen: onOpen,
    );
    return _database!;
  }

  @override
  Future<int> create(
    String table,
    Map<String, Object?> values, {
    ConflictAlgorithm conflictAlgorithm = ConflictAlgorithm.abort,
  }) async {
    final database = await open();
    return database.insert(
      table,
      values,
      conflictAlgorithm: conflictAlgorithm,
    );
  }

  @override
  Future<List<Map<String, Object?>>> read(
    String table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) async {
    final database = await open();
    return database.query(
      table,
      distinct: distinct,
      columns: columns,
      where: where,
      whereArgs: whereArgs,
      groupBy: groupBy,
      having: having,
      orderBy: orderBy,
      limit: limit,
      offset: offset,
    );
  }

  @override
  Future<Map<String, Object?>?> readById(
    String table,
    Object id, {
    String idColumn = 'id',
    List<String>? columns,
  }) async {
    final rows = await read(
      table,
      columns: columns,
      where: '\$idColumn = ?',
      whereArgs: <Object?>[id],
      limit: 1,
    );

    return rows.isEmpty ? null : rows.first;
  }

  @override
  Future<int> update(
    String table,
    Map<String, Object?> values, {
    String? where,
    List<Object?>? whereArgs,
    ConflictAlgorithm conflictAlgorithm = ConflictAlgorithm.abort,
  }) async {
    final database = await open();
    return database.update(
      table,
      values,
      where: where,
      whereArgs: whereArgs,
      conflictAlgorithm: conflictAlgorithm,
    );
  }

  @override
  Future<int> delete(
    String table, {
    String? where,
    List<Object?>? whereArgs,
  }) async {
    final database = await open();
    return database.delete(
      table,
      where: where,
      whereArgs: whereArgs,
    );
  }

  @override
  Future<int> count(
    String table, {
    String? where,
    List<Object?>? whereArgs,
  }) async {
    final database = await open();
    final results = await database.query(
      table,
      columns: const <String>['COUNT(*) AS total'],
      where: where,
      whereArgs: whereArgs,
    );
    if (results.isEmpty) {
      return 0;
    }

    final total = results.first['total'];
    if (total is int) {
      return total;
    }
    if (total is num) {
      return total.toInt();
    }

    return int.tryParse(total.toString()) ?? 0;
  }

  @override
  Future<T> transaction<T>(Future<T> Function(Transaction txn) action) async {
    final database = await open();
    return database.transaction<T>(action);
  }

  @override
  Future<void> close() async {
    await _database?.close();
    _database = null;
  }
}
''';
  }

  String _notificationServiceDart() {
    return '''
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import '../logging/app_logger.dart';

class AppNotificationService {
  AppNotificationService({required AppLogger logger}) : _logger = logger;

  final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();
  final AppLogger _logger;

  Future<void> initialize() async {
    const settings = InitializationSettings(
      android: AndroidInitializationSettings('@mipmap/ic_launcher'),
      iOS: DarwinInitializationSettings(),
    );
    await _plugin.initialize(settings);
    _logger.info('Notifications initialized.');
  }
}
''';
  }

  String _appStringsDart(ResolvedGenerationConfig resolved) {
    return '''
class AppStrings {
  const AppStrings._();

  static const String appName = '${resolved.appName}';
  static const String architectureReady = 'Architecture scaffold is ready.';
}
''';
  }

  String _boxConstantsDart() {
    return '''
class BoxConstants {
  const BoxConstants._();

  static const String appCache = 'app_cache';
  static const String sessionCache = 'session_cache';
}
''';
  }

  String _routeConstantsDart() {
    return '''
class RouteConstants {
  const RouteConstants._();

  static const String home = '/home';
  static const String root = '/';
  static const String settings = '/settings';
}
''';
  }

  String _sessionConstantsDart() {
    return '''
class SessionConstants {
  const SessionConstants._();

  static const String accessTokenKey = 'access_token';
  static const String refreshTokenKey = 'refresh_token';
}
''';
  }

  String _designTokensDart() {
    return '''
import 'package:flutter/material.dart';

class DesignTokens {
  const DesignTokens._();

  static const Color backgroundColor = Color(0xFFF5F7FB);
  static const Color primaryColor = Color(0xFF0F6EFD);
  static const double radiusMd = 14;
  static const double spacingMd = 16;
  static const Color surfaceColor = Colors.white;
}
''';
  }

  String _dateFormatExtensionDart() {
    return '''
import 'package:intl/intl.dart';

extension DateFormatExtension on DateTime {
  String toAppDate([String pattern = 'dd MMM yyyy']) {
    return DateFormat(pattern).format(this);
  }
}
''';
  }

  String _stringExtensionsDart() {
    return '''
extension StringExtensions on String {
  String get trimmedOrEmpty => trim();

  bool get isBlank => trimmedOrEmpty.isEmpty;
}
''';
  }

  String _appSessionDart() {
    return '''
import 'package:equatable/equatable.dart';

class AppSession extends Equatable {
  const AppSession({
    this.accessToken,
    this.refreshToken,
    this.userId,
  });

  final String? accessToken;
  final String? refreshToken;
  final String? userId;

  @override
  List<Object?> get props => <Object?>[accessToken, refreshToken, userId];
}
''';
  }

  String _screenUtilsDart() {
    return '''
import 'package:flutter/widgets.dart';

extension ScreenUtils on BuildContext {
  Size get screenSize => MediaQuery.sizeOf(this);
  double get screenWidth => screenSize.width;
  double get screenHeight => screenSize.height;
}
''';
  }

  String _customAppBarDart() {
    return '''
import 'package:flutter/material.dart';

class CustomAppBar extends StatelessWidget implements PreferredSizeWidget {
  const CustomAppBar({
    required this.title,
    super.key,
  });

  final String title;

  @override
  Size get preferredSize => const Size.fromHeight(kToolbarHeight);

  @override
  Widget build(BuildContext context) {
    return AppBar(
      title: Text(title),
      centerTitle: false,
    );
  }
}
''';
  }

  String _customDialogDart() {
    return '''
import 'package:flutter/material.dart';

class CustomDialog {
  const CustomDialog._();

  static Future<void> show(
    BuildContext context, {
    required String title,
    required String message,
  }) {
    return showDialog<void>(
      context: context,
      builder: (_) => AlertDialog(
        title: Text(title),
        content: Text(message),
        actions: <Widget>[
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }
}
''';
  }

  String _customSnackbarDart() {
    return '''
import 'package:flutter/material.dart';

class CustomSnackbar {
  const CustomSnackbar._();

  static void show(BuildContext context, String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message)),
    );
  }
}
''';
  }

  String _customTextFieldDart() {
    return '''
import 'package:flutter/material.dart';

class CustomTextField extends StatelessWidget {
  const CustomTextField({
    super.key,
    this.controller,
    this.hintText,
    this.obscureText = false,
  });

  final TextEditingController? controller;
  final String? hintText;
  final bool obscureText;

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: controller,
      obscureText: obscureText,
      decoration: InputDecoration(hintText: hintText),
    );
  }
}
''';
  }

  String _loadingViewDart() {
    return '''
import 'package:flutter/material.dart';

class LoadingView extends StatelessWidget {
  const LoadingView({super.key});

  @override
  Widget build(BuildContext context) {
    return const Center(
      child: CircularProgressIndicator(),
    );
  }
}
''';
  }

  String _featuresReadme() {
    return '''
# Features

Add domain-specific modules here. Features may depend on `core` and `shared`, but `core` must never import `features`.
''';
  }

  String _architectureSmokeTestDart(ResolvedGenerationConfig resolved) {
    return '''
import 'package:flutter_test/flutter_test.dart';
import '${_packageImport(resolved, 'core/config/env.dart')}';
import '${_packageImport(resolved, 'core/config/flavor.dart')}';

void main() {
  test('environment defaults are available', () {
    final env = AppEnv.fromEnvironment();

    expect(env.appName, isNotEmpty);
    expect(Flavor.values, isNotEmpty);
  });
}
''';
  }

  String _analysisOptionsYaml() {
    return '''
include: package:flutter_lints/flutter.yaml
''';
  }

  String _buildYaml() {
    return '''
targets:
  \$default:
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          - lib/**
''';
  }

  String _shorebirdReadme(ResolvedGenerationConfig resolved) {
    final releaseFlavor = _releaseFlavor(resolved);

    return '''
# Shorebird Release Notes

This project was scaffolded with Shorebird release helpers for the `$releaseFlavor` flavor.

## Suggested setup

1. Install the Shorebird CLI.
2. Run `shorebird init` inside the Flutter app.
3. Copy values from `shorebird.yaml.example` into your real `shorebird.yaml` if you want a checked-in template.
4. Verify Firebase, Crashlytics, and release signing are already working before shipping patches.

## Common commands

```bash
shorebird release android --flavor $releaseFlavor
shorebird release ios --flavor $releaseFlavor
shorebird patch android --flavor $releaseFlavor
shorebird patch ios --flavor $releaseFlavor
```

## Notes

- Replace the placeholder Shorebird app id before your first release.
- If you support multiple release flavors, duplicate the commands above for the flavors you actually ship.
- Keep your Flutter and Shorebird CLI versions aligned in CI so patches stay reproducible.
''';
  }

  String _shorebirdYamlExample(ResolvedGenerationConfig resolved) {
    final releaseFlavor = _releaseFlavor(resolved);

    return '''
app_id: your-shorebird-app-id
flavor: $releaseFlavor
release_notes:
  default: Initial release generated by flutter_archgen.
platforms:
  android:
    enabled: true
  ios:
    enabled: true
''';
  }

  String _fastlaneGemfile() {
    return '''
source 'https://rubygems.org'

gem 'fastlane'
''';
  }

  String _fastlaneAppfile(ResolvedGenerationConfig resolved) {
    final applicationId = _defaultApplicationId(resolved);

    return '''
app_identifier(ENV['APP_IDENTIFIER'] || '$applicationId')
package_name(ENV['ANDROID_APPLICATION_ID'] || '$applicationId')
apple_id(ENV['APP_STORE_CONNECT_EMAIL'] || 'you@example.com')
itc_team_id(ENV['APP_STORE_CONNECT_TEAM_ID'] || 'YOUR_TEAM_ID')
team_id(ENV['DEVELOPER_PORTAL_TEAM_ID'] || 'YOUR_TEAM_ID')
''';
  }

  String _fastlaneFastfile(ResolvedGenerationConfig resolved) {
    final applicationId = _defaultApplicationId(resolved);
    final releaseFlavor = _releaseFlavor(resolved);

    return '''
default_platform(:android)

def flutter_build_runner
  sh('dart run build_runner build')
end

def flutter_prepare
  sh('flutter pub get')
  flutter_build_runner
end

platform :android do
  desc 'Build an Android app bundle for the configured flavor'
  lane :build_bundle do |options|
    flavor = options[:flavor] || ENV['FLUTTER_FLAVOR'] || '$releaseFlavor'
    flutter_prepare
    sh("flutter build appbundle --flavor #{flavor} --dart-define=FLAVOR=#{flavor}")
  end

  desc 'Upload the generated app bundle to Google Play internal track'
  lane :internal do |options|
    flavor = options[:flavor] || ENV['FLUTTER_FLAVOR'] || '$releaseFlavor'
    build_bundle(flavor: flavor)
    supply(
      track: options[:track] || 'internal',
      package_name: ENV['ANDROID_APPLICATION_ID'] || '$applicationId',
      aab: options[:aab] || "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
      json_key: ENV['SUPPLY_JSON_KEY'],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

platform :ios do
  desc 'Build an IPA for the configured flavor'
  lane :build_ipa do |options|
    flavor = options[:flavor] || ENV['FLUTTER_FLAVOR'] || '$releaseFlavor'
    flutter_prepare
    sh("flutter build ipa --flavor #{flavor} --dart-define=FLAVOR=#{flavor}")
  end

  desc 'Upload the generated IPA to TestFlight'
  lane :testflight do |options|
    flavor = options[:flavor] || ENV['FLUTTER_FLAVOR'] || '$releaseFlavor'
    build_ipa(flavor: flavor)
    pilot(
      ipa: options[:ipa] || '../build/ios/ipa/*.ipa',
      skip_waiting_for_build_processing: true
    )
  end
end
''';
  }

  String _fastlaneReadme(ResolvedGenerationConfig resolved) {
    final releaseFlavor = _releaseFlavor(resolved);

    return '''
# Fastlane Setup

Fastlane scaffolding was generated for the `$releaseFlavor` release flavor.

## Suggested setup

1. Install Ruby and Bundler on your machine or CI image.
2. Run `bundle install`.
3. Fill in the real identifiers and team settings in `fastlane/Appfile`.
4. Provide credentials through environment variables instead of committing secrets.

## Example lanes

```bash
bundle exec fastlane android build_bundle flavor:$releaseFlavor
bundle exec fastlane android internal flavor:$releaseFlavor
bundle exec fastlane ios build_ipa flavor:$releaseFlavor
bundle exec fastlane ios testflight flavor:$releaseFlavor
```

## Required environment variables

- `APP_IDENTIFIER` for the iOS bundle id override.
- `ANDROID_APPLICATION_ID` for the Android application id override.
- `SUPPLY_JSON_KEY` for Google Play upload lanes.
- `APP_STORE_CONNECT_EMAIL`, `APP_STORE_CONNECT_TEAM_ID`, and `DEVELOPER_PORTAL_TEAM_ID` for iOS lanes.

## Notes

- The generated lanes run `flutter pub get` and `dart run build_runner build` before builds.
- Adjust build commands if your app uses a different entrypoint or additional dart defines.
- Keep store credentials in CI secrets, not in the repository.
''';
  }

  String _generatedReadmeSection(ResolvedGenerationConfig resolved) {
    final nextSteps = <String>[
      '1. Run `flutter pub get`.',
      '2. Run `dart run build_runner build`.',
      '3. Add Firebase config files if Firebase support was enabled.',
      '4. Re-run `flutterfire configure` after enabling Crashlytics.',
      if (resolved.config.enableShorebird)
        '5. Review `tool/release/shorebird/README.md` and run `shorebird init`.',
      if (resolved.config.enableFastlane)
        '${resolved.config.enableShorebird ? 6 : 5}. Review `fastlane/README.md` and run `bundle install`.',
      '${resolved.config.enableShorebird && resolved.config.enableFastlane
          ? 7
          : resolved.config.enableShorebird || resolved.config.enableFastlane
          ? 6
          : 5}. Set `SENTRY_DSN` and copy `sentry.properties.example` to `sentry.properties` if Sentry is enabled.',
      '${resolved.config.enableShorebird && resolved.config.enableFastlane
          ? 8
          : resolved.config.enableShorebird || resolved.config.enableFastlane
          ? 7
          : 6}. Replace placeholder routes with real features.',
      '${resolved.config.enableShorebird && resolved.config.enableFastlane
          ? 9
          : resolved.config.enableShorebird || resolved.config.enableFastlane
          ? 8
          : 7}. Run `flutter analyze`.',
    ];

    return '''
## Generated Architecture

This app was scaffolded with `flutter_archgen`.

### Next steps

${nextSteps.join('\n')}
''';
  }
}
